# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['denite']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

# deoplete.nvim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

# gtags
[[plugins]]
repo  = 'lighttiger2505/gtags.vim'

[[plugins]]
repo  = 'thinca/vim-qfreplace'
on_source = ['gtags.vim'] 

#[[plugins]]
#repo = 'jsfaint/gen_tags.vim'
#hook_add = '''
#  let g:gen_tags#gtags_auto_gen = 1
#'''
#on_source = ['gtags.vim'] 

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
  nmap <silent> [denite]<C-D> :Denite-buffer-name=gtags_completion gtags_completion<CR>
'''
on_source = ['gtags.vim'] 

# nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['nerdtree']

# python
[[plugins]]
repo  = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo  = 'hdima/python-syntax'
on_ft = ['python']

[[plugins]]
repo  = 'hdima/python-syntax'
on_ft = ['python']

## markdown
#[[plugins]]
#repo = 'tyru/open-browser.vim'
#on_ft = ['md', 'markdown']
#
#[[plugins]]
#repo = 'kannokanno/previm'
#on_ft = ['md', 'markdown']
#
#[[plugins]]
#repo = 'plasticboy/vim-markdown'
#on_ft = ['md', 'markdown']

## html
#[[plugins]]
#repo = 'othree/html5.vim'
#on_ft = ['html']
#
## css 
#[[plugins]]
#repo = 'hail2u/vim-css3-syntax'
#on_ft = ['css']
#
## json 
#[[plugins]]
#repo = 'elzr/vim-json'
#on_ft = ['json']
#hook_add = '''
#let g:vim_json_syntax_conceal = 0
#'''
#
## toml
#[[plugins]]
#repo = 'cespare/vim-toml'
#on_ft = ['toml']

